name: Update README Stats

on:
  schedule:
    - cron: "0 */6 * * *" # Atualiza a cada 6h
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate GitHub Stats
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_1 }}
        run: |
          curl -H "Authorization: token $GITHUB_TOKEN" \
              -o stats.svg \
              "https://github-readme-stats.vercel.app/api?username=jouw-dev&show_icons=true&count_private=true&include_all_commits=true&theme=codeSTACKr"

      - name: Commit and push
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add stats.svg
          git diff --quiet && git diff --staged --quiet || git commit -m "Update GitHub stats"
          git push

